export const refs = {
    eventsList: document.querySelector('.js-events-list'),
    lightbox: document.querySelector('.js-lightbox'),
    lightboxContent: document.querySelector('.lightbox__content'),
    closeLightboxBtn: document.querySelector('[data-action="close-lightbox"]'),
    searchQuery: document.querySelector('.search-input'),
    lightboxBackdrop: document.querySelector('section.js-lightbox'),
    eventCard: document.querySelector('.event-card'),
    searchCountry: document.querySelector('.js-select2'),
    headerContainer: document.querySelector('.header-content'),
    authBtn: document.querySelector('.auth-btn'),
    authModal: document.querySelector('.auth-modal'),
    searchForm: document.querySelector('.searchForm'),
    authForm: document.querySelector('#auth-form'),
    creatingAcc: document.querySelector('.creating-acc'),
    registerForm: document.querySelector('#register-form'),
    openTeamModal: document.querySelector('.footer-team__name'),
    closeTeamModal: document.querySelector('#teammates'),
    backdrop: document.querySelector('.backdrop'),
    sentinel: document.querySelector('#sentinel'),
    goTop: document.getElementById("go-top"),
    topEvents: document.querySelector('.top-events'),
    favoriteBtn: document.querySelector('#favorite'),
    calendarBtn: document.querySelector('.calendar-btn'),
    calendar: document.querySelector('.calendar'),
    iconClose: document.querySelector('.icon-close'),
    favoriteBtn: document.querySelectorAll('#favorite'),
    fav: document.querySelector('.fav-events'),
    location: document.querySelector('.location'),
    local: document.querySelector('.local'),
    mainCalendar: document.querySelector('#main-calendar'),
    favoriteModal: document.querySelector('.fav-modal'),
    logsBtn: document.querySelector('.logsBtn'),
    loadCalendar: document.querySelector('.loadCalendar'),
    mapRef: document.querySelector('#map'),
  
}

export default refs;